package com.sattaporn.model;
// Generated Aug 5, 2017 2:00:18 PM by Hibernate Tools 5.2.3.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Customer generated by hbm2java
 */
@Entity
@Table(name = "customer", schema = "public")
public class Customer implements java.io.Serializable {

	private int id;
	private String name;
	private String lname;
	private String address;
	private String workAddress;
	private String sirName;
	private String fullName;

	public Customer() {
	}

	public Customer(int id) {
		this.id = id;
	}

	public Customer(int id, String name, String lname, String address, String workAddress, String sirName,
			String fullName) {
		this.id = id;
		this.name = name;
		this.lname = lname;
		this.address = address;
		this.workAddress = workAddress;
		this.sirName = sirName;
		this.fullName = fullName;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "name", length = 50)
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "lname")
	public String getLname() {
		return this.lname;
	}

	public void setLname(String lname) {
		this.lname = lname;
	}

	@Column(name = "address")
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "work_address")
	public String getWorkAddress() {
		return this.workAddress;
	}

	public void setWorkAddress(String workAddress) {
		this.workAddress = workAddress;
	}

	@Column(name = "sir_name", length = 20)
	public String getSirName() {
		return this.sirName;
	}

	public void setSirName(String sirName) {
		this.sirName = sirName;
	}

	@Column(name = "full_name")
	public String getFullName() {
		return this.fullName;
	}

	public void setFullName(String fullName) {
		this.fullName = fullName;
	}

}
