package com.sattaporn.model;
// Generated Aug 25, 2017 1:46:49 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * EmailTransaction generated by hbm2java
 */
@Entity
@Table(name = "email_transaction", schema = "public")
public class EmailTransaction implements java.io.Serializable {

	private int id;

	public EmailTransaction() {
	}

	public EmailTransaction(int id) {
		this.id = id;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

}
