package com.sattaporn.model;
// Generated Aug 25, 2017 1:46:49 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * MenuPermission generated by hbm2java
 */
@Entity
@Table(name = "menu_permission", schema = "public")
public class MenuPermission implements java.io.Serializable {

	private int id;
	private Menu menu;
	private String name;
	private Set permissions = new HashSet(0);

	public MenuPermission() {
	}

	public MenuPermission(int id) {
		this.id = id;
	}

	public MenuPermission(int id, Menu menu, String name, Set permissions) {
		this.id = id;
		this.menu = menu;
		this.name = name;
		this.permissions = permissions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_id")
	public Menu getMenu() {
		return this.menu;
	}

	public void setMenu(Menu menu) {
		this.menu = menu;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menuPermission", targetEntity=Permission.class)
	public Set getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set permissions) {
		this.permissions = permissions;
	}

}
