package com.sattaporn.model;
// Generated Aug 25, 2017 1:46:49 PM by Hibernate Tools 5.2.5.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Menu generated by hbm2java
 */
@Entity
@Table(name = "menu", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Menu implements java.io.Serializable {

	private int id;
	private String code;
	private String name;
	private String createBy;
	private Date createDate;
	private String updateBy;
	private Date updateDate;
	private Set menuPermissions = new HashSet(0);

	public Menu() {
	}

	public Menu(int id) {
		this.id = id;
	}

	public Menu(int id, String code, String name, String createBy, Date createDate, String updateBy, Date updateDate,
			Set menuPermissions) {
		this.id = id;
		this.code = code;
		this.name = name;
		this.createBy = createBy;
		this.createDate = createDate;
		this.updateBy = updateBy;
		this.updateDate = updateDate;
		this.menuPermissions = menuPermissions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", unique = true, length = 20)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@Column(name = "name")
	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	@Column(name = "create_by")
	public String getCreateBy() {
		return this.createBy;
	}

	public void setCreateBy(String createBy) {
		this.createBy = createBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "create_date", length = 13)
	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	@Column(name = "update_by")
	public String getUpdateBy() {
		return this.updateBy;
	}

	public void setUpdateBy(String updateBy) {
		this.updateBy = updateBy;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "update_date", length = 13)
	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "menu", targetEntity = MenuPermission.class)
	public Set getMenuPermissions() {
		return this.menuPermissions;
	}

	public void setMenuPermissions(Set menuPermissions) {
		this.menuPermissions = menuPermissions;
	}

}
