package com.sattaporn.model;
// Generated Aug 25, 2017 1:46:49 PM by Hibernate Tools 5.2.5.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Permission generated by hbm2java
 */
@Entity
@Table(name = "permission", schema = "public")
public class Permission implements java.io.Serializable {

	private int id;
	private MenuPermission menuPermission;
	private Role role;

	public Permission() {
	}

	public Permission(int id) {
		this.id = id;
	}

	public Permission(int id, MenuPermission menuPermission, Role role) {
		this.id = id;
		this.menuPermission = menuPermission;
		this.role = role;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "menu_permission_id")
	public MenuPermission getMenuPermission() {
		return this.menuPermission;
	}

	public void setMenuPermission(MenuPermission menuPermission) {
		this.menuPermission = menuPermission;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "role_id")
	public Role getRole() {
		return this.role;
	}

	public void setRole(Role role) {
		this.role = role;
	}

}
