package com.sattaporn.model;
// Generated Aug 25, 2017 1:46:49 PM by Hibernate Tools 5.2.5.Final

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "role", schema = "public", uniqueConstraints = @UniqueConstraint(columnNames = "code"))
public class Role implements java.io.Serializable {

	private int id;
	private String code;
	private Set userRoles = new HashSet(0);
	private Set permissions = new HashSet(0);

	public Role() {
	}

	public Role(int id) {
		this.id = id;
	}

	public Role(int id, String code, Set userRoles, Set permissions) {
		this.id = id;
		this.code = code;
		this.userRoles = userRoles;
		this.permissions = permissions;
	}

	@Id

	@Column(name = "id", unique = true, nullable = false)
	public int getId() {
		return this.id;
	}

	public void setId(int id) {
		this.id = id;
	}

	@Column(name = "code", unique = true)
	public String getCode() {
		return this.code;
	}

	public void setCode(String code) {
		this.code = code;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role", targetEntity=UserRole.class)
	public Set getUserRoles() {
		return this.userRoles;
	}

	public void setUserRoles(Set userRoles) {
		this.userRoles = userRoles;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "role", targetEntity=Permission.class)
	public Set getPermissions() {
		return this.permissions;
	}

	public void setPermissions(Set permissions) {
		this.permissions = permissions;
	}

}
